global class INT_Contact
{
    webservice String sourceId;
    webservice String destinationId;
    webservice String title;
    webservice String firstName;
    webservice String middleName;
    webservice String abbreviatedname;
    webservice String lastName;
    webservice String maidenName;  
    webservice String gender; 
    webservice Date   dateOfBirth;
    webservice String governmentId;
    webservice String passportNo;
    webservice String maritalStatus;
    webservice String firstLanguage;
    webservice String ethnicalOrigin;
    webservice String yearOfGraduation;
    webservice String specialRequirements;
    webservice Datetime lastModifiedDate; 

    webservice INT_EmailAddresses emailAddresses;

    webservice INT_Addresses addresses;

    webservice INT_TelephoneNumbers numbers;

}