global class INT_CourseProduct
{
    webService String sourceId;
    webService String destinationId;
    webService String name;
    webService String code;
    webservice INT_Qualification qualification;
    webservice INT_Institution institution;
    webservice Date startDate;
    webservice String enrolmentType;
    webservice String enrolmentStatus;
    webservice String enrolmentReference;
    webservice INT_CancelEnrolment cancelEnrolment;

}