/*******************************************************************************************************************
* Apex Class Name  : tIU_ContactTest
* Version          : 1.0 
* Created Date     : 30 March 2015
* Function         : Test Class of the tIU_ContactTest
* Modification Log :
*
* Developer                                Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*   Accenture IDC                          31/03/2015              Created Initial Version
*******************************************************************************************************************/

@isTest                  
public class tIU_ContactTest{
 static testMethod void myTest() {
 
 
 }
}